######################################################################
# Automatically generated by qmake (2.01a) mar. juil. 16 10:52:22 2013
######################################################################

TEMPLATE = app
TARGET = mvision.bin
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp mainWindow.cpp
HEADERS += mainWindow.h
